### ISSUE TITLE
Automatically present queues added to SQS

### ISSUE THREAD

**Issue by petromir** [roribio/alpine-sqs#10]
Thanks for creating this project.

In order to view custom queues I need to edit at least 2 configuration files.

I think it would be better if the UI automatically present the queues added to SQS. One option is to use https://docs.aws.amazon.com/cli/latest/reference/sqs/list-queues.html

**Comment by roribio** [comment]
That's a great suggestion. Thank you :)

**Comment by Requaos** [comment]
I found a similar need, so I modified the `sqs-init.sh` file with some scripting to generate the queues, driven by environmental variables.
