### ISSUE TITLE
Use tag with your docker-image

### ISSUE THREAD

**Issue by giraudvalentin** [roribio/alpine-sqs#26]
Hello,

Can you please use tag with your repo and docker images ?

We want to integrate this image but some build break so we need versioning with tag.

Thank you in advance.

Regards,

**Comment by roribio** [comment]
Hi @giraudvalentin,

Thanks for bringing this up, you're spot on 👍 

After yesterday's build broke, it's painfully clear not tagging bit us yesterday.

I will take care of this shortly.

Thanks,
Ronald

**Comment by roribio** [comment]
Update: I created a manual release but I'm having trouble with Docker Hub. I'm creating a rule to create an image based of a tag and it's not saving it.

I will try again later.

**Comment by roribio** [comment]
Alright guys, created a new release, tagged it and updated automated build rules on docker hub.

Commits to master will build and tag an image as `latest` and all new releases will build and tag an image with the release `tag`.

Let me know if there's anything else I should look at.

Thanks!
