### ISSUE TITLE
How can I make the queues persist between starting and stopping docker?

### ISSUE THREAD

**Issue by justinmchase** [roribio/alpine-sqs#28]
Presumably the queues are persisted to disk somewhere and I just need to volume mount the right folder. Do you know what the path is?

**Comment by villasv** [comment]
AFAIK, ElasticMQ (the actual message broker implementation that is compatible with SQS) uses an in-memory storage for messages. Not sure if that changed recently or it's just a default and can be configured though.

**Comment by roribio** [comment]
Hey @justinmchase, thanks for your question.

I looked at ElasticMQ's source going on @villasv comment and he is correct. If you look at the reference configuration file for the server you'll find that the only supported storage type at the moment is in-memory.
-- https://github.com/softwaremill/elasticmq/blob/795ac31f8e24a22af25fbef4cc8bc7f7155a82b7/server/src/main/resources/reference.conf#L3

I'm guessing a possible work around is writing a process that retrieves the messages from the queue and writes them to disk before the server shuts down and restores them when you boot it back up.

Cheers,
Ronald
